[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tompy"
authors = [{name = "Tom", email = "nanticj@users.noreply.github.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">=3.10"
dependencies = [
    "Bottleneck",
    "finance-datareader",
    "loguru",
    "numpy",
    "pandas",
    "pydantic",
    "python-dotenv",
    "pytz",
    "scipy",
]

[project.urls]
Home = "https://github.com/nanticj/tompy"

[project.optional-dependencies]
develop = [
    "black",
    "flit",
    "isort",
    "mypy",
    "pylint",
    "pytest",
]

[tool.isort]
profile = "black"
line_length = 79

[tool.black]
line-length = 79

[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.pylint.'MESSAGES CONTROL']
enable = "all"
disable = """ \
    C0103, \
    C0114, \
    C0115, \
    C0116, \
    C0209, \
    R0801, \
    R0902, \
    R0903, \
    R0904, \
    R0913, \
    R0914, \
    R0915, \
    W0621, \
    W0622, \
    """
