[tool.poetry]
name = "pybiolib"
version = "1.1.132"
description = "BioLib Python Client"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/biolib"
keywords = ["biolib"]
authors = [
    "biolib <hello@biolib.com>",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
packages = [
    { include = "biolib" },
]
include = [
    "README.md",
    "LICENSE",
]

[tool.poetry.scripts]
biolib = "biolib:call_cli"

[tool.poetry.dependencies]
appdirs = ">=1.4.3"
docker = ">=5.0.3"
flask = ">=2.0.1"
flask-cors = ">=3.0.10"
gunicorn = ">=20.1.0"
importlib-metadata = ">=1.6.1"
pycryptodome = ">=3.9.9"
pyjwt = ">=2.3.0"
python = "^3.6.3"
pyyaml = ">=5.3.1"
requests = ">=2.25.1"
spython = ">=0.1.18"
typing_extensions = { version = ">=3.10.0", python = "<3.8" }
typing_inspect = { version = "^0.5.0", python = "<3.8" }
rich = "^12.4.4"

[tool.poetry.dev-dependencies]
mypy = "==0.910"
pylint = "==2.7.4"
pytest = "==6.2.4"
types-Flask = "==1.1.1"
types-PyYAML = "==5.4.3"
types-requests = "==2.25.0"
types-termcolor = "==0.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
