[tool.poetry]
name = "datamonk-prefect-tasks"
version = "0.1.5"
description = ""
authors = ["Vit Mrnavek <vit.mrnavek@datamonk.cz>"]
packages = [
    { include = "datamonk/prefect_tasks" }
    ]

[tool.poetry.dependencies]
python = ">=3.9.0,<3.10.0"
datamonk-utils = "^0.1.2"
datamonk-scriptorium = "^0.5.5"
datamonk-invest-tools = "^0.1.2"
prefect = "^1.2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
