[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
authors = [
  {name = "CarryMeRookie", email = "dx121@ic.ac.uk"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
description = "A small example package"
license = {file = "LICENSE"}
name = "ImpactEffect"
readme = "README.md"
requires-python = ">=3.7"
version = "0.0.3"

[project.urls]
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
"Homepage" = "https://github.com/pypa/sampleproject"
