[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyspark-dbscan"
version = "1.0.2"
description = "An \"Efficient\" Implementation of DBSCAN on PySpark"
readme = "README.md"
dependencies = [
    "graphframes>=0.6",
    "ipykernel>=6.15.1",
    "ipython>=8.4.0",
    "jupyter-client>=7.3.4",
    "jupyter-core>=4.11.1",
    "matplotlib>=3.3.0",
    "numpy>=1.19.0",
    "pandas>=1.4.3",
    "py4j>=0.10.9",
    "pyspark>=3.1.2",
    "scikit-learn>=0.24.2",
    "scipy>=1.7.0",
    "seaborn>=0.11.2",
    "sklearn>=0.0"
]
requires-python = ">=3.6"
